name: Update Scholar Counts

on:
  schedule:
    - cron: "0 6 1 * *"  # Run at 06:00 UTC on the 1st of every month    
  workflow_dispatch:      # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python scholar_counts.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add scholar_counts.csv scholar_counts.png
          git commit -m "Weekly update of scholar counts [ci skip]" || echo "No changes"
          git push
